[project]
name = "{{cookiecutter.project_name}}"
version = "{{cookiecutter.version}}"
description = "{{cookiecutter.friendly_name}}"
authors = [{ name = "{{cookiecutter.author}}", email = "{{cookiecutter.email}}"}]
requires-python = ">=3.9,<4.0"
readme = "README.md"
license = "{{cookiecutter.license}}"
classifiers = [
    "{{cookiecutter.development_status}}",
]
dependencies = [
    "click>=8.0.1",
    "loguru>=0.7.2,<8",
    "platformdirs>=4.2.2,<5",
    "typing-extensions>=4.9.0,<5"
]

[project.scripts]
{{cookiecutter.project_name}} = "{{cookiecutter.package_name}}.__main__:main"

[project.urls]
Homepage = "https://github.com/{{cookiecutter.github_user}}/{{cookiecutter.project_name}}"
Repository = "https://github.com/{{cookiecutter.github_user}}/{{cookiecutter.project_name}}"
Documentation = "https://{{cookiecutter.project_name}}.readthedocs.io"
Changelog = "https://github.com/{{cookiecutter.github_user}}/{{cookiecutter.project_name}}/releases"

[dependency-groups]
dev = [
    "Pygments>=2.10.0",
    "certifi>=2024.7.4",
    "coverage>=6.2",
    "darglint>=1.8.1",
    "furo>=2021.11.12",
    "isort>=5.10.1",
    "mypy>=0.930",
    "pep8-naming>=0.12.1",
    "pre-commit>=2.16.0",
    "pre-commit-hooks>=4.1.0",
    "pyupgrade>=2.29.1",
    "sphinx>=4.3.2",
    "sphinx-autobuild>=2021.3.14",
    "sphinx-click>=3.0.2",
    "typeguard>=2.13.3",
    "xdoctest[colors]>=0.15.10",
    "myst-parser>=0.16.1",
    "ruff>=0.11.5,<0.12",
    "pip-audit>=2.9.0,<3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
